-- 1. Crear la tabla de invitados
create table if not exists public.invitados_ftm520 (
    id bigint generated by default as identity primary key,
    nombre text not null,
    nombre_busqueda text not null,
    pases integer default 1,
    pases_seleccionados integer default 1,
    estado text default 'Pendiente',
    acompanantes text,
    whatsapp text,
    comentario text,
    respuesta_novios text,
    fecha_solicitud timestamptz default now(),
    fecha_confirmacion timestamptz,
    created_at timestamptz default now(),

    -- Restricción de unicidad por nombre normalizado
    constraint uq_invitados_nombre unique (nombre_busqueda)
);

-- 2. Crear índice para optimizar las búsquedas por nombre normalizado
create index if not exists idx_invitados_nombre 
on public.invitados_ftm520 (nombre_busqueda);

-- 3. Habilitar la seguridad a nivel de filas (RLS)
alter table public.invitados_ftm520 enable row level security;

-- 4. Crear política de acceso público (anon) para permitir SELECT, INSERT, UPDATE y DELETE
create policy "Permitir acceso publico total a invitados_ftm520"
on public.invitados_ftm520
for all
using (true)
with check (true);

-- 5. Habilitar la tabla en la publicación de Realtime para actualizaciones en vivo
alter publication supabase_realtime add table public.invitados_ftm520;